pub mod analysis;
pub mod cgp;
pub mod diagnostic_render;
pub mod diagnostics;
pub mod docs;
pub mod format;
pub mod lsp;
pub mod manifest;
#[cfg(feature = "mcp")]
pub mod mcp;
pub mod parse;
pub mod prelude;
pub mod repl;
pub mod resolver;
pub mod test_runner;
pub mod vm;
