<section class="hero" aria-labelledby="hero-heading">
	<h1 id="hero-heading" class="wordmark">Baseline</h1>
	<div class="hero-split">
		<div class="hero-left">
			<p class="hero-subtitle">A safe, performant, concise language for software hand-crafted by humans or generated by AI agents.</p>
			<ul class="hero-pillars">
				<li class="hero-pillar">
					<em>The type is the spec</em>
					<span>Correctness is provable, not hopeful</span>
				</li>
				<li class="hero-pillar">
					<em>Effects are data</em>
					<span>Side effects are capabilities, not surprises</span>
				</li>
				<li class="hero-pillar">
					<em>Built for humans and machines</em>
					<span>Generate it, compile it, trust it</span>
				</li>
			</ul>
		</div>
		<div class="hero-right">
			<pre><code>{@html `<span class="kw">fn</span> <span class="fn">fetch_user!</span><span class="punct">(</span><span class="fn">id</span><span class="op">:</span> <span class="type">Int</span><span class="punct">)</span> <span class="op">-&gt;</span> <span class="effect">{Http, Console}</span> <span class="type">Result&lt;String, String&gt;</span> <span class="op">=</span>
  <span class="type">Console</span><span class="punct">.</span><span class="fn">print!</span><span class="punct">(</span><span class="str">"Fetching user \${id}"</span><span class="punct">)</span>
  <span class="kw">let</span> <span class="fn">response</span> <span class="op">=</span> <span class="type">Http</span><span class="punct">.</span><span class="fn">get!</span><span class="punct">(</span><span class="str">"/users/\${id}"</span><span class="punct">)</span><span class="op">?</span>
  <span class="kw">match</span> <span class="fn">response</span><span class="punct">.</span><span class="fn">status</span>
    <span class="num">200</span> <span class="op">-&gt;</span> <span class="type">Ok</span><span class="punct">(</span><span class="fn">response</span><span class="punct">.</span><span class="fn">body</span><span class="punct">)</span>
    <span class="num">404</span> <span class="op">-&gt;</span> <span class="type">Err</span><span class="punct">(</span><span class="str">"User not found"</span><span class="punct">)</span>
    <span class="fn">code</span> <span class="op">-&gt;</span> <span class="type">Err</span><span class="punct">(</span><span class="str">"HTTP \${code}"</span><span class="punct">)</span>`}</code></pre>
			<div class="btn-group" style="margin-top: var(--sp-4);">
				<a href="#start" class="button button-primary">Get Started</a>
				<a href="https://github.com/baseline-lang" class="button">View on GitHub</a>
			</div>
		</div>
	</div>
</section>
